### PR TITLE
fix #1288: correlation id in body for upload to blob

### LINKED ISSUE #1288: Maximum file name length in blob storage
We notice that the file name presents a limit equal to 139 characters.
In fact, we always receive an HTTP 400 error if the file name exceeds this limit

```
Failure in HTTP communication: server reply code is 400
HTTP Response:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
HTTP code was 400
unable to execute HTTPAPIEX_ExecuteRequest
IoTHubClient_LL_UploadToBlob_step3 failed
```
Could you please confirm this limit and give us more details?

### PR DESCRIPTION
**Pull request by danewalton**
# Checklist
- [ ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [ ] This pull-request is submitted against the `master` branch. 
  - [ ] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
  - [ ] I have squashed my changes into one with a clear description of the change.

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

# Description of the solution

### CODE REVIEW

File: iothub_client/src/iothub_client_ll_uploadtoblob.c [hunk 1]
```diff
@@ -814,14 +825,25 @@ IOTHUB_CLIENT_RESULT IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl(IOTHUB_CLIE
 
                                             /*do step 3*/ /*try*/
                                             /*Codes_SRS_IOTHUBCLIENT_LL_02_091: [ If step 2 fails without establishing an HTTP dialogue, then the HTTP message body shall look like: ]*/
-                                            if (BUFFER_build(responseToIoTHub, (const unsigned char*)FILE_UPLOAD_FAILED_BODY, sizeof(FILE_UPLOAD_FAILED_BODY) / sizeof(FILE_UPLOAD_FAILED_BODY[0])) == 0)
+                                            STRING_HANDLE failed_response = STRING_construct_sprintf(FILE_UPLOAD_FAILED_BODY, STRING_c_str(correlationId));
+                                            if(failed_response == NULL)
+                                            {
+                                                LogError("STRING_construct_sprintf failed");
```
Comment (CIPop) [inline iothub_client/src/iothub_client_ll_uploadtoblob.c]: This message is identical to the one above so we can't really tell which one failed.

File: iothub_client/src/iothub_client_ll_uploadtoblob.c [hunk 2]
```diff
@@ -42,8 +42,8 @@ int snprintf(char * s, size_t n, const char * format, ...)
 #endif
 
 /*Codes_SRS_IOTHUBCLIENT_LL_02_085: [ IoTHubClient_LL_UploadToBlob shall use the same authorization as step 1. to prepare and perform a HTTP request with the following parameters: ]*/
-#define FILE_UPLOAD_FAILED_BODY "{ \"isSuccess\":false, \"statusCode\":-1,\"statusDescription\" : \"client not able to connect with the server\" }"
-#define FILE_UPLOAD_ABORTED_BODY "{ \"isSuccess\":false, \"statusCode\":-1,\"statusDescription\" : \"file upload aborted\" }"
+#define FILE_UPLOAD_FAILED_BODY "{ \"correlationId\":\"%s\", \"isSuccess\":false, \"statusCode\":-1,\"statusDescription\" : \"client not able to connect with the server\" }"
```
Comment (CIPop) [inline iothub_client/src/iothub_client_ll_uploadtoblob.c]: I don't think we need this anymore since we have other places where the formatting string is used.
We should instead use the same formatting string and the arguments separately (i.e. "false"|"true", `statusDescription`s, etc).

File: iothub_client/tests/iothubclient_uploadtoblob_e2e/iothubclient_uploadtoblob_e2e.c [hunk 3]
```diff
@@ -240,13 +240,13 @@ IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_RESULT uploadToBlobGetDataEx(IOTHUB_CLIENT_FI
...
     ASSERT_ARE_EQUAL(UPLOADTOBLOB_CALLBACK_STATUS, *callbackStatus, UPLOADTOBLOB_CALLBACK_PENDING);
-    ASSERT_ARE_EQUAL(int, (int)result, (int)FILE_UPLOAD_OK);
+    ASSERT_ARE_EQUAL(int, (int)FILE_UPLOAD_OK, (int)result);
 
     static char* uploadData0 = "AAA-";
     static char* uploadData1 = "BBBBB-";
     static char* uploadData2 = "CCCCCC-";
 
-    ASSERT_ARE_EQUAL(int, (int)Lock(updateBlobTestLock), (int)LOCK_OK);
+    ASSERT_ARE_EQUAL(int, (int)LOCK_OK, (int)Lock(updateBlobTestLock));
```
Comment (CIPop) [inline iothub_client/tests/iothubclient_uploadtoblob_e2e/iothubclient_uploadtoblob_e2e.c]: 👍

File: iothub_client/tests/iothubclient_uploadtoblob_e2e/iothubclient_uploadtoblob_e2e.c [hunk 4]
```diff
@@ -240,13 +240,13 @@ IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_RESULT uploadToBlobGetDataEx(IOTHUB_CLIENT_FI
 
     UPLOADTOBLOB_CALLBACK_STATUS* callbackStatus = (UPLOADTOBLOB_CALLBACK_STATUS*)context;
     ASSERT_ARE_EQUAL(UPLOADTOBLOB_CALLBACK_STATUS, *callbackStatus, UPLOADTOBLOB_CALLBACK_PENDING);
-    ASSERT_ARE_EQUAL(int, (int)result, (int)FILE_UPLOAD_OK);
```
Comment (CIPop) [inline iothub_client/tests/iothubclient_uploadtoblob_e2e/iothubclient_uploadtoblob_e2e.c]: Anything we can do in e2e to verify we're correctly sending the correlationID? Is there any information flown back from hub after the Blob upload has failed?

File: iothub_client/src/iothub_client_ll_uploadtoblob.c [hunk 5]
```diff
@@ -538,15 +538,15 @@ static int IoTHubClient_LL_UploadToBlob_step1and2(IOTHUB_CLIENT_LL_UPLOADTOBLOB_
...
-static int IoTHubClient_LL_UploadToBlob_step3(IOTHUB_CLIENT_LL_UPLOADTOBLOB_HANDLE_DATA* upload_data, STRING_HANDLE correlationId, HTTPAPIEX_HANDLE iotHubHttpApiExHandle, HTTP_HEADERS_HANDLE requestHttpHeaders, BUFFER_HANDLE messageBody)
+static int IoTHubClient_LL_UploadToBlob_step3(IOTHUB_CLIENT_LL_UPLOADTOBLOB_HANDLE_DATA* upload_data, HTTPAPIEX_HANDLE iotHubHttpApiExHandle, HTTP_HEADERS_HANDLE requestHttpHeaders, BUFFER_HANDLE messageBody)
 {
     int result;
     /*here is step 3. depending on the outcome of step 2 it needs to inform IoTHub about the file upload status*/
     /*if step 1 failed, there's nothing that step 3 needs to report.*/
     /*this POST "tries" to happen*/
 
     /*Codes_SRS_IOTHUBCLIENT_LL_02_085: [ IoTHubClient_LL_UploadMultipleBlocksToBlob(Ex) shall use the same authorization as step 1. to prepare and perform a HTTP request with the following parameters: ]*/
-    STRING_HANDLE relativePathNotification = STRING_construct_sprintf("/devices/%s/files/notifications/%s%s", upload_data->deviceId, STRING_c_str(correlationId), API_VERSION);
```
[the remark this answers is not in the document]
Comment (danewalton) [reply iothub_client/src/iothub_client_ll_uploadtoblob.c]: No you can send the correlation ID in the url or the body. We had the URL but the problem was if someone had a filename that was really long in the URL, it would cause issues when the correlation was also there. So to give more room for the file name, we just put the correlation ID in the body. Thats also the way that the documentation [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload) states to do it.

File: iothub_client/src/iothub_client_ll_uploadtoblob.c (hunk 1 above)
Comment (danewalton) [reply iothub_client/src/iothub_client_ll_uploadtoblob.c]: the LogError expands to put the line number and file where it failed to give greater context.

File: iothub_client/tests/iothubclient_uploadtoblob_e2e/iothubclient_uploadtoblob_e2e.c (hunk 4 above)
Comment (danewalton) [reply iothub_client/tests/iothubclient_uploadtoblob_e2e/iothubclient_uploadtoblob_e2e.c]: We do since the service rejects it if the correlation id is wrong.

File: iothub_client/src/iothub_client_ll_uploadtoblob.c (hunk 2 above)
Comment (danewalton) [reply iothub_client/src/iothub_client_ll_uploadtoblob.c]: good idea thanks for that. pushed a change to simplify this.

File: iothub_client/src/iothub_client_ll_uploadtoblob.c [hunk 6]
```diff
@@ -788,23 +787,38 @@ IOTHUB_CLIENT_RESULT IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl(IOTHUB_CLIE
                                             /*Codes_SRS_IOTHUBCLIENT_LL_99_008: [ If step 2 is aborted by the client, then the HTTP message body shall look like:  ]*/
                                             LogInfo("Blob_UploadFromSasUri aborted file upload");
 
-                                            if (BUFFER_build(responseToIoTHub, (const unsigned char*)FILE_UPLOAD_ABORTED_BODY, sizeof(FILE_UPLOAD_ABORTED_BODY) / sizeof(FILE_UPLOAD_ABORTED_BODY[0])) == 0)
+                                            STRING_HANDLE aborted_response = STRING_construct_sprintf(RESPONSE_BODY_FORMAT,
+                                                                                        STRING_c_str(correlationId),
+                                                                                        (const unsigned char*)"false",
+                                                                                        (const unsigned char*)"-1",
+                                                                                        (const unsigned char*)"file upload aborted");
```
Comment (mamokarz) [inline iothub_client/src/iothub_client_ll_uploadtoblob.c]: Please create global constants for these strings.

Comment (danewalton) [reply iothub_client/src/iothub_client_ll_uploadtoblob.c]: changed thanks
