### PR TITLE
Fix #587: avoid new GCC 8.2 warning (s/strncpy/memcpy/)

### LINKED ISSUE #587: GCC 8.2 generates warnings when compiling serializer/src/commanddecoder.c
Related issue: https://github.com/Azure/azure-c-shared-utility/issues/174

When compiling serializer/src/commanddecoder.c with 

    gcc (Debian 8.2.0-3) 8.2.0

I'm getting warnings (and thus errors (-Werror)) due the use of strncpy. GCC is unable to figure out that the length-arg is correctly guarded (or is it not)?

```
In function ‘DecodeAndExecuteModelAction.isra.0’,
    inlined from ‘ScanActionPathAndExecuteAction’ at azure-iot-sdk-c/serializer/src/commanddecoder.c:441:26,
    inlined from ‘DecodeCommand’ at azure-iot-sdk-c/serializer/src/commanddecoder.c:607:22,
    inlined from ‘CommandDecoder_ExecuteCommand’ at azure-iot-sdk-c/serializer/src/commanddecoder.c:679:26:
azure-iot-sdk-c/serializer/src/commanddecoder.c:194:13: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
         if (strncpy(tempStr, actionName, strLength - 1) == NULL)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
azure-iot-sdk-c/serializer/src/commanddecoder.c: In function ‘CommandDecoder_ExecuteCommand’:
azure-iot-sdk-c/serializer/src/commanddecoder.c:176:24: note: length computed here
     size_t strLength = strlen(actionName);
```

`strncpy()` could be replace with `memcpy()` here, I think.

### PR DESCRIPTION
**Pull request by pboettch**
GCC 8.2 is not able to determine that the length is OK for dst
and thus moans about the usage of strncpy.

How it is done, memcpy seems more appropriate to be used.

Maybe in the future this code can be even more simplified.

 

# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `master` branch. 
  - [x] I have merged the latest `master` branch prior to submission and re-merged as needed after I took any feedback.
  - [x] I have squashed my changes into one with a clear description of the change.

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

# Description of the solution

### CODE REVIEW

File: serializer/src/commanddecoder.c [hunk 1]
```diff
@@ -191,7 +191,7 @@ static EXECUTE_COMMAND_RESULT DecodeAndExecuteModelAction(COMMAND_DECODER_HANDLE
 #ifdef _MSC_VER
 #pragma warning(suppress: 6324) /* We intentionally use here strncpy */ 
 #endif
-        if (strncpy(tempStr, actionName, strLength - 1) == NULL)
+        if (memcpy(tempStr, actionName, strLength - 1) == NULL)
```
Comment (ewertons) [inline serializer/src/commanddecoder.c]: Hi @pboettch ,
there was a bug in this part of the code that we had planned to fix, but with your change now it needs to be fixed in a different way.

To allow us to merge your change in and record your contribution, could you make the following changes please?

1. Change the memcpy call to: ```if (memcpy(tempStr, actionName, strLength + 1) == NULL)```

(note the strLength + 1 instead of strLength - 1)

and

2. Remove ```tempStr[strLength - 1] = 0;``` (on line 209 below).

Comment (jebrando) [reply serializer/src/commanddecoder.c]: @pboettch I shall take your branch and apply the changes that Ewerton suggested.  I need to make the change as soon as possible.  I will merge this change into the SDK.

Thanks,
Jelani

Comment (pboettch) [reply serializer/src/commanddecoder.c]: Just got up. I see you merged it into your memcpy-fix branch. Do not hesitate to request more changes. If I can be helpful, I will be.
